name: vonage_voice
description: "Native Vonage voice calling for Flutter. Includes full background support, native call UI (CallKit/ConnectionService), and in-call controls."
version: 1.0.0
homepage: https://github.com/ashiqu-ali/vonage_voice
repository: https://github.com/ashiqu-ali/vonage_voice
issue_tracker: https://github.com/ashiqu-ali/vonage_voice/issues


funding:
  - https://www.buymeacoffee.com/ashiqu.ali

topics:
  - voip
  - vonage
  - callkit
  - telecom
  - communication

environment:
  sdk: '>=3.10.8 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ashiquali.vonage_voice
        pluginClass: VonageVoicePlugin
      ios:
        pluginClass: VonageVoicePlugin